
project:
  type: website
  output-dir: docs
  preview:
    port: 5896
    browser: true

website:
  page-navigation: true
  title: "Hello, I'm Jae."
  description: "The personal website of Dr. Jae Yeon Kim"
  site-url: https://jaeyk.github.io/
  favicon: images/favicon/favicon-32x32.png
  repo-url: https://github.com/jaeyk/jaeyk.github.io
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: true
  google-analytics: G-Q5LW45FBCB
  page-footer:
    left: "&copy; Copyright 2026, Jae Yeon Kim"
    right: 
      - icon: github
        href: https://github.com/jaeyk/jaeyk.github.io

  navbar:
    #background: dark
    #foreground: light
    right:
      - text: "Home"
        href: index.qmd
        
      - text: "CV"
        href: CV_Jae_Yeon_Kim.pdf
        
      - text: "Talks"
        href: talks/talks.qmd 
        
      - text: "Awards"
        href: awards/awards.qmd
        
      - text: "Publications"
        href: publications/pubs.qmd
        
      - text: "Book"
        href: book_projects/books.qmd
        
      - text: "Software"
        href: software/software.qmd
        
      - text: "Data"
        href: datasets/data.qmd
        
      - text: "Teaching"
        href: teaching/teaching.qmd
        
      - text: "Community"
        href: community_building/community.qmd
        
      - text: "Personal"
        href: essays/essays.qmd
        
      - text: "Office Hour"
        href: office_hour/office_hour.qmd
        
format:
  html:
    css: styles.scss
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    highlight-style: github
    anchor-sections: true
    smooth-scroll: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
          <link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png">
          <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
          <link rel="manifest" href="/images/favicon/site.webmanifest">

